openapi: "3.0.1"
info:
  title: "Data Management API"
  version: "v1"
paths:
  /api/v1/advisors:
    get:
      tags:
        - "Advisors"
      responses:
        "500":
          description: "Server Error"
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/AdvisorDto"
    post:
      tags:
        - "Advisors"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdvisorCreationDto"
      responses:
        "500":
          description: "Server Error"
        "201":
          description: "Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdvisorDto"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Error"
  /api/v1/advisors/{id}:
    get:
      tags:
        - "Advisors"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "500":
          description: "Server Error"
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdvisorDto"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      tags:
        - "Advisors"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdvisorUpdateDto"
      responses:
        "500":
          description: "Server Error"
        "204":
          description: "No Content"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - "Advisors"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "500":
          description: "Server Error"
        "204":
          description: "No Content"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    AdvisorCreationDto:
      type: "object"
      properties:
        firstName:
          type: "string"
          nullable: true
        lastName:
          type: "string"
          nullable: true
        address:
          type: "string"
          nullable: true
        phone:
          type: "string"
          nullable: true
        sin:
          type: "string"
          nullable: true
      additionalProperties: false
    AdvisorDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        firstName:
          type: "string"
          nullable: true
        lastName:
          type: "string"
          nullable: true
        sin:
          type: "string"
          nullable: true
        address:
          type: "string"
          nullable: true
        phone:
          type: "string"
          nullable: true
        healthStatus:
          type: "string"
          nullable: true
      additionalProperties: false
    AdvisorUpdateDto:
      type: "object"
      properties:
        firstName:
          type: "string"
          nullable: true
        lastName:
          type: "string"
          nullable: true
        address:
          type: "string"
          nullable: true
        phone:
          type: "string"
          nullable: true
      additionalProperties: false
    Error:
      type: "object"
      properties:
        code:
          type: "string"
          nullable: true
        message:
          type: "string"
          nullable: true
      additionalProperties: false
